-- 1. Create the Database
CREATE DATABASE IF NOT EXISTS easy_pos;
USE easy_pos;

-- 2. Create the Categoria Table (Parent table)
CREATE TABLE categoria (
    CATEGORIA_ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    PRIMARY KEY (CATEGORIA_ID)
);

-- 3. Create the Producto Table
CREATE TABLE producto (
    PRODUCTO_ID INT NOT NULL AUTO_INCREMENT,
    CATEGORIA_ID INT NOT NULL,
    CODIGO_SKU VARCHAR(50) NOT NULL,
    NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
    DESCRIPCION_PRODUCTO VARCHAR(255),
    PRECIO_VENTA DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    PRECIO_COSTO DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    STOCK_ACTUAL INT NOT NULL DEFAULT 0,
    STOCK_MIN INT NOT NULL DEFAULT 0,
    PRODUCTO_ESTADO SMALLINT NOT NULL DEFAULT 1, -- 1 = Active, 0 = Inactive
    PRODUCTO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (PRODUCTO_ID),
    UNIQUE KEY (CODIGO_SKU),
    -- Foreign Key Constraint
    CONSTRAINT fk_categoria 
        FOREIGN KEY (CATEGORIA_ID) 
        REFERENCES categoria(CATEGORIA_ID)
        ON DELETE CASCADE
);

-- 4. Insert some initial data (Optional)
INSERT INTO categoria (NOMBRE_CATEGORIA) VALUES ('General'), ('Electrónica'), ('Alimentos');